(deftheme RDKDeeperBlue
  "Created 2024-03-06.")

(custom-theme-set-faces
 'RDKDeeperBlue
 '(default ((((class color) (min-colors 89)) (:background "#181a26" :foreground "gray80"))))
 '(cursor ((((class color) (min-colors 89)) (:background "green"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "CadetBlue1"))))
 '(highlight ((((class color) (min-colors 89)) (:background "DodgerBlue4"))))
 '(region ((((class color) (min-colors 89)) (:background "#103050"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((((class color) (min-colors 88) (background light)) (:extend t :background "yellow1")) (((class color) (min-colors 88) (background dark)) (:extend t :background "SkyBlue4")) (((class color) (min-colors 16) (background light)) (:extend t :background "yellow")) (((class color) (min-colors 16) (background dark)) (:extend t :background "SkyBlue4")) (((class color) (min-colors 8)) (:extend t :foreground "black" :background "cyan")) (t (:inverse-video t))))
 '(trailing-whitespace ((((class color) (background light)) (:background "red1")) (((class color) (background dark)) (:background "red1")) (t (:inverse-video t))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "LightCoral"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "gray50"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "gray50"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "moccasin"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "goldenrod"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "gold"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:weight bold))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:weight bold))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "burlywood"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "CadetBlue1"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "SeaGreen2"))))
 '(font-lock-warning-face ((t (:inherit (error)))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "cyan1"))))
 '(link-visited ((t (:foreground "violet" :inherit (link)))))
 '(fringe ((((class color) (min-colors 89)) (:background "black"))))
 '(header-line ((t (:box nil :foreground "grey90" :background "grey20" :inherit (mode-line)))))
 '(tooltip ((t (:foreground "black" :background "lightyellow" :inherit (variable-pitch)))))
 '(mode-line ((((class color) (min-colors 89)) (:background "gray75" :foreground "black" :box (:line-width 1 :style released-button)))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:weight bold :background nil :foreground "blue4"))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:background "gray40" :foreground "black" :box (:line-width 1 :color "gray40" :style nil)))))
 '(isearch ((((class color) (min-colors 89)) (:background "coral2" :foreground "white"))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "cadetblue" :foreground "white"))))
 '(match ((((class color) (min-colors 89)) (:background "DeepPink4"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(compilation-column-number ((((class color) (min-colors 89)) (:foreground "LightGreen"))))
 '(compilation-error ((((class color) (min-colors 89)) (:foreground "Red1"))))
 '(compilation-info ((((class color) (min-colors 89)) (:weight normal :foreground "LightSkyBlue"))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "LightGreen"))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:foreground "blue4"))))
 '(dired-marked ((((class color) (min-colors 89)) (:background "dodgerblue3" :foreground "white"))))
 '(error ((((class color) (min-colors 89)) (:foreground "red"))))
 '(info-header-node ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(info-header-xref ((((class color) (min-colors 89)) (:foreground "SeaGreen2"))))
 '(info-menu-header ((((class color) (min-colors 89)) (:family "helv" :weight bold))))
 '(info-node ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(info-xref ((((class color) (min-colors 89)) (:foreground "SeaGreen2"))))
 '(outline-1 ((((class color) (min-colors 89)) (:foreground "SkyBlue1"))))
 '(outline-2 ((((class color) (min-colors 89)) (:foreground "CadetBlue1"))))
 '(outline-3 ((((class color) (min-colors 89)) (:foreground "LightSteelBlue1"))))
 '(outline-4 ((((class color) (min-colors 89)) (:foreground "turquoise2"))))
 '(outline-5 ((((class color) (min-colors 89)) (:foreground "aquamarine1"))))
 '(success ((((class color) (min-colors 89)) (:foreground "SeaGreen2"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "Yellow"))))
 '(hl-line ((t (:background "#292b37"))))
 '(tab-bar ((t (:background "black" :foreground "white"))))
 '(tab-bar-tab ((t (:background "#333333" :foreground "grey80"))))
 '(tab-bar-tab-inactive ((t (:background "#181a26" :inherit tab-bar)))))

(provide-theme 'RDKDeeperBlue)
